// ============================================================
//  CHIBO.JS - DANH SÁCH TỔ CHỨC ĐẢNG
//  Nguồn: Danh mục TC CS Đảng - Đảng viên
//  Đảng ủy phường Thanh Khê
// ============================================================
const DS_NHOM = [
{
  id: "nhom1",
  ten: "I. ĐẢNG ỦY CƠ SỞ",
  danhSach: [
    "Đảng ủy các cơ quan Đảng",
    "Đảng ủy UBND phường",
    "Đảng ủy Công an phường",
    "Đảng ủy Trung tâm Y tế khu vực Thanh Khê",
    "Đảng ủy Trường Thể dục Thể Thao Đà Nẵng",
    "Đảng ủy Trường Cao đẳng Thương Mại",
    "Đảng ủy Công ty Cổ phần xây dựng công trình 512",
    "Đảng ủy Công ty Cổ phần Dược DANAPHA",
    "Đảng ủy Công ty Cổ phần Dệt May 29/3",
    "Đảng ủy Công ty Cổ phần In và Dịch vụ Đà Nẵng",
    "Đảng ủy Bưu điện thành phố Đà Nẵng",
    "Đảng ủy Công ty TNHH MTV Thương Mại Quảng Nam - Đà Nẵng",
    "Đảng ủy Ngân hàng TMCP Công Thương Việt Nam - Chi nhánh Đà Nẵng"
  ]
},
{
  id: "nhom2",
  ten: "II. UBKT ĐẢNG ỦY CƠ SỞ",
  danhSach: [
    "UBKT Đảng ủy các cơ quan Đảng",
    "UBKT Đảng ủy UBND phường",
    "UBKT Đảng ủy Công an phường",
    "UBKT Đảng ủy Trung tâm Y tế khu vực Thanh Khê",
    "UBKT Đảng ủy Trường Thể dục Thể Thao Đà Nẵng",
    "UBKT Đảng ủy Trường Cao đẳng Thương Mại",
    "UBKT Đảng ủy Công ty Cổ phần xây dựng công trình 512",
    "UBKT Đảng ủy Công ty Cổ phần Dược DANAPHA",
    "UBKT Đảng ủy Công ty Cổ phần Dệt May 29/3",
    "UBKT Đảng ủy Công ty Cổ phần In và Dịch vụ Đà Nẵng",
    "UBKT Đảng ủy Bưu điện thành phố Đà Nẵng",
    "UBKT Đảng ủy Công ty TNHH MTV Thương Mại Quảng Nam - Đà Nẵng",
    "UBKT Đảng ủy Ngân hàng TMCP Công Thương Việt Nam - Chi nhánh Đà Nẵng"
  ]
},
{
  id: "nhom3",
  ten: "III. CHI BỘ CƠ SỞ",
  danhSach: [
    "Chi bộ Trường THPT Thanh Khê",
    "Chi bộ Trường THPT Thái Phiên",
    "Chi bộ Trung tâm Giáo dục thường xuyên số 2",
    "Chi bộ Trung tâm Huấn luyện Vận động viên trẻ Quốc gia Đà Nẵng",
    "Chi bộ Trường THPT Quang Trung (tư thục)",
    "Chi bộ Cty Cổ phần Xây lắp Điện và Cơ khí mạ Đà Nẵng",
    "Chi bộ Cty Cổ phần Dịch vụ bảo vệ An Ninh",
    "Chi bộ Cty CP Tư vấn và Phát triển kỹ thuật Tài nguyên nước",
    "Chi bộ Cty Cổ phần Túi xách Đà Nẵng",
    "Chi bộ Cty TNHH Dịch vụ Bảo vệ an ninh Quốc Đô",
    "Chi bộ Cty Cổ phần Tư vấn xây dựng và Đầu tư Trường Định",
    "Chi bộ Ngân hàng TMCP An Bình Chi nhánh Đà Nẵng",
    "Chi bộ Cty Bảo hiểm PJICO Đà Nẵng",
    "Chi bộ Ngân hàng TMCP Tiên Phong Chi nhánh Đà Nẵng",
    "Chi bộ VPĐD Miền Trung Ngân Hàng TMCP Kỹ Thương VN",
    "Chi bộ Cty Bảo Minh Đà Nẵng",
    "Chi bộ quân sự phường",
    "Chi bộ Trạm Y tế",
    "Chi bộ Trường Mầm non Cẩm Tú",
    "Chi bộ Trường Mầm non Tuổi Hoa",
    "Chi bộ Trường Mầm non Mẫu Đơn",
    "Chi bộ Trường Mầm non Phong Lan",
    "Chi bộ Trường Mầm non Hải Đường",
    "Chi bộ Trường Mầm non Thủy Tiên",
    "Chi bộ Trường Mầm non Cẩm Nhung",
    "Chi bộ Trường Mầm non Hoàng Mai",
    "Chi bộ Trường Mầm non Tường Vy",
    "Chi bộ Trường Tiểu học Đoàn Thị Điểm",
    "Chi bộ Trường Tiểu học Lê Quang Sung",
    "Chi bộ Trường Tiểu học Huỳnh Ngọc Huệ",
    "Chi bộ Trường Tiểu học Lê Văn Tám",
    "Chi bộ Trường Tiểu học Dũng Sĩ Thanh Khê",
    "Chi bộ Trường Tiểu học Nguyễn Đức Cảnh",
    "Chi bộ Trường Tiểu học Hà Huy Tập",
    "Chi bộ Trường Tiểu học Nguyễn Trung Trực",
    "Chi bộ Trường Tiểu học Đinh Bộ Lĩnh",
    "Chi bộ Trường Tiểu học Điện Biên Phủ",
    "Chi bộ Trường Tiểu học Trần Cao Vân",
    "Chi bộ Trường Tiểu học Nguyễn Bá Ngọc",
    "Chi bộ Trường Tiểu học Hàm Nghi",
    "Chi bộ Trường Tiểu học Hoa Lư",
    "Chi bộ Trường THCS Phan Đình Phùng",
    "Chi bộ Trường THCS Huỳnh Thúc Kháng",
    "Chi bộ Trường THCS Đỗ Đăng Tuyển",
    "Chi bộ Trường THCS Nguyễn Chơn",
    "Chi bộ Trường THCS Hoàng Diệu",
    "Chi bộ Trường THCS Lê Thị Hồng Gấm",
    "Chi bộ Trường THCS Nguyễn Duy Hiệu",
    "Chi bộ Trường THCS Nguyễn Trãi",
    "Chi bộ Trường THCS Chu Văn An",
    "Chi bộ Trường THCS Nguyễn Thị Minh Khai",
    "Chi bộ BIDV Văn phòng đại diện tại TP Đà Nẵng"
  ]
},
{
  id: "nhom4",
  ten: "IV. CHI BỘ TRỰC THUỘC",
  danhSach: [
    "Chi bộ 1 TAM THUẬN",
    "Chi bộ 2 TAM THUẬN",
    "Chi bộ 3 TAM THUẬN",
    "Chi bộ 4 TAM THUẬN",
    "Chi bộ 5 TAM THUẬN",
    "Chi bộ 6 TAM THUẬN",
    "Chi bộ 7 TAM THUẬN",
    "Chi bộ 8 TAM THUẬN",
    "Chi bộ 9 TAM THUẬN",
    "Chi bộ 10 TÂN CHÍNH",
    "Chi bộ 11 TÂN CHÍNH",
    "Chi bộ 12 TÂN CHÍNH",
    "Chi bộ 13 TÂN CHÍNH",
    "Chi bộ 14 TÂN CHÍNH",
    "Chi bộ 15 TÂN CHÍNH",
    "Chi bộ 16 VĨNH TRUNG",
    "Chi bộ 17 VĨNH TRUNG",
    "Chi bộ 18 VĨNH TRUNG",
    "Chi bộ 19 VĨNH TRUNG",
    "Chi bộ 20 VĨNH TRUNG",
    "Chi bộ 21 VĨNH TRUNG",
    "Chi bộ 22 VĨNH TRUNG",
    "Chi bộ 23 THẠC GIÁN",
    "Chi bộ 24 THẠC GIÁN",
    "Chi bộ 25 THẠC GIÁN",
    "Chi bộ 26 THẠC GIÁN",
    "Chi bộ 27 THẠC GIÁN",
    "Chi bộ 28 THẠC GIÁN",
    "Chi bộ 29 THẠC GIÁN",
    "Chi bộ 30 THẠC GIÁN",
    "Chi bộ 31 THẠC GIÁN",
    "Chi bộ 32 XUÂN HÀ",
    "Chi bộ 33 XUÂN HÀ",
    "Chi bộ 34 XUÂN HÀ",
    "Chi bộ 35 XUÂN HÀ",
    "Chi bộ 36 XUÂN HÀ",
    "Chi bộ 37 XUÂN HÀ",
    "Chi bộ 38 XUÂN HÀ",
    "Chi bộ 39 XUÂN HÀ",
    "Chi bộ 40 CHÍNH GIÁN",
    "Chi bộ 41 CHÍNH GIÁN",
    "Chi bộ 42 CHÍNH GIÁN",
    "Chi bộ 43 CHÍNH GIÁN",
    "Chi bộ 44 CHÍNH GIÁN",
    "Chi bộ 45 CHÍNH GIÁN",
    "Chi bộ 46 CHÍNH GIÁN",
    "Chi bộ 47 CHÍNH GIÁN",
    "Chi bộ 48 CHÍNH GIÁN",
    "Chi bộ 49 THANH KHÊ ĐÔNG",
    "Chi bộ 50 THANH KHÊ ĐÔNG",
    "Chi bộ 51 THANH KHÊ ĐÔNG",
    "Chi bộ 52 THANH KHÊ ĐÔNG",
    "Chi bộ 53 THANH KHÊ ĐÔNG",
    "Chi bộ 54 HÒA KHÊ",
    "Chi bộ 55 HÒA KHÊ",
    "Chi bộ 56 HÒA KHÊ",
    "Chi bộ 57 HÒA KHÊ",
    "Chi bộ 58 HÒA KHÊ",
    "Chi bộ 59 HÒA KHÊ",
    "Chi bộ 60 HÒA KHÊ",
    "Chi bộ 61 HÒA KHÊ",
    "Chi bộ 62 HÒA KHÊ",
    "Chi bộ 63 HÒA KHÊ",
    "Chi bộ 64 HÒA KHÊ",
    "Chi bộ 65 THANH KHÊ TÂY",
    "Chi bộ 66 THANH KHÊ TÂY",
    "Chi bộ 67 THANH KHÊ TÂY",
    "Chi bộ 68 THANH KHÊ TÂY",
    "Chi bộ 69 THANH KHÊ TÂY",
    "Chi bộ 70 THANH KHÊ TÂY",
    "Chi bộ 71 THANH KHÊ TÂY",
    "Chi bộ 72 THANH KHÊ TÂY",
    "Chi bộ 73 THANH KHÊ TÂY",
    "Chi bộ 74 THANH KHÊ TÂY",
    "Chi bộ 75 THANH KHÊ TÂY",
    "Chi bộ 76 THANH KHÊ TÂY",
    "Chi bộ 77 THANH KHÊ TÂY",
    "Chi bộ 78 THANH KHÊ TÂY",
    "Chi bộ 79 THANH KHÊ TÂY",
    "Chi bộ 80 THANH KHÊ TÂY"
  ]
},
{
  id: "nhom5",
  ten: "V. CHI BỘ DOANH NGHIỆP",
  danhSach: [
    "Chi bộ Công ty Cổ phần Xây dựng Giao thông 503",
    "Chi bộ Trường Trung cấp Chuyên nghiệp Ý Việt",
    "Chi bộ Công ty Cổ phần Sinh học Minh Hồng",
    "Chi bộ Tổng Công ty Miền Trung - CTCP",
    "Chi bộ Công ty TNHH Kiểm toán & Dịch vụ tin học Moore Aisc tại Đà Nẵng",
    "Chi bộ Công ty Cổ phần Giám định Á Việt"
  ]
}
];

// Danh sách phẳng toàn bộ (dùng cho code.gs)
const DS_CHI_BO = DS_NHOM.flatMap(nhom => nhom.danhSach);

// Danh sách phẳng kèm nhóm (dùng cho giao diện dropdown nhóm)
const DS_CHI_BO_FULL = DS_NHOM.flatMap(nhom =>
  nhom.danhSach.map(ten => ({ nhom: nhom.ten, ten }))
);
