// ============================================================
//  CHIBO.JS - DANH SÁCH TỔ CHỨC ĐẢNG (2 PHẦN)
//  Dùng cho index.html (ô chọn/tìm kiếm Chi bộ phía trình duyệt)
//  Nguồn: "DANH SÁCH CÁC CHI, ĐẢNG BỘ TRỰC THUỘC THAM GIA CUỘC THI
//  TRỰC TUYẾN" - Đảng ủy phường Thanh Khê
//  ĐỒNG BỘ với chibo.gs (bên Apps Script) - sửa 1 bên thì nhớ sửa
//  bên còn lại cho khớp tên, nếu không tỷ lệ dự thi sẽ bị tính sai.
// ============================================================
const DS_NHOM = [
{
  id: "nhom1",
  ten: "I. ĐẢNG BỘ TRỰC THUỘC",
  danhSach: [
    "Đảng ủy Công an phường",
    "Đảng ủy Trung tâm Y tế khu vực Thanh Khê",
    "Đảng ủy Công Ty Cổ phần Xây dựng Công trình 512",
    "Đảng ủy Công ty Cổ phần In và Dịch vụ Đà Nẵng",
    "Đảng ủy Công ty Cổ phần Dệt may 29/3",
    "Đảng ủy Công ty Cổ phần Dược Danapha",
    "Đảng ủy Trường Cao đẳng Thương mại",
    "Đảng ủy Trường Đại học Thể dục thể thao Đà Nẵng",
    "Đảng bộ Bưu điện thành phố Đà Nẵng",
    "Đảng bộ Công ty TNHH MTV Thương Mại Quảng Nam - Đà Nẵng",
    "Đảng bộ Ngân hàng TMCP Công Thương Việt Nam - Chi nhánh Đà Nẵng",
  ]
},
{
  id: "nhom2",
  ten: "II. CHI BỘ TRỰC THUỘC",
  danhSach: [
    // --- Chi bộ khu dân cư (đưa lên đầu) ---
    "1 Tam Thuận",
    "2 Tam Thuận",
    "3 Tam Thuận",
    "4 Tam Thuận",
    "5 Tam Thuận",
    "6 Tam Thuận",
    "7 Tam Thuận",
    "8 Tam Thuận",
    "9 Tam Thuận",
    "10 Tân Chính",
    "11 Tân Chính",
    "12 Tân Chính",
    "13 Tân Chính",
    "14 Tân Chính",
    "15 Tân Chính",
    "16 Vĩnh Trung",
    "17 Vĩnh Trung",
    "18 Vĩnh Trung",
    "19 Vĩnh Trung",
    "20 Vĩnh Trung",
    "21 Vĩnh Trung",
    "22 Vĩnh Trung",
    "23 Thạc Gián",
    "24 Thạc Gián",
    "25 Thạc Gián",
    "26 Thạc Gián",
    "27 Thạc Gián",
    "28 Thạc Gián",
    "29 Thạc Gián",
    "30 Thạc Gián",
    "31 Thạc Gián",
    "32 Xuân Hà",
    "33 Xuân Hà",
    "34 Xuân Hà",
    "35 Xuân Hà",
    "36 Xuân Hà",
    "37 Xuân Hà",
    "38 Xuân Hà",
    "39 Xuân Hà",
    "40 Chính Gián",
    "41 Chính Gián",
    "42 Chính Gián",
    "43 Chính Gián",
    "44 Chính Gián",
    "45 Chính Gián",
    "46 Chính Gián",
    "47 Chính Gián",
    "48 Chính Gián",
    "49 Thanh Khê Đông",
    "50 Thanh Khê Đông",
    "51 Thanh Khê Đông",
    "52 Thanh Khê Đông",
    "53 Thanh Khê Đông",
    "54 Hòa Khê",
    "55 Hòa Khê",
    "56 Hòa Khê",
    "57 Hòa Khê",
    "58 Hòa Khê",
    "59 Hòa Khê",
    "60 Hòa Khê",
    "61 Hòa Khê",
    "62 Hòa Khê",
    "63 Hòa Khê",
    "64 Hòa Khê",
    "65 Thanh Khê Tây",
    "66 Thanh Khê Tây",
    "67 Thanh Khê Tây",
    "68 Thanh Khê Tây",
    "69 Thanh Khê Tây",
    "70 Thanh Khê Tây",
    "71 Thanh Khê Tây",
    "72 Thanh Khê Tây",
    "73 Thanh Khê Tây",
    "74 Thanh Khê Tây",
    "75 Thanh Khê Tây",
    "76 Thanh Khê Tây",
    "77 Thanh Khê Tây",
    "78 Thanh Khê Tây",
    "79 Thanh Khê Tây",
    "80 Thanh Khê Tây",
    // --- Chi bộ cơ quan, đơn vị, doanh nghiệp, trường học ---
    "Chi bộ Ban Xây dựng Đảng Đảng ủy phường",
    "Chi bộ Văn phòng Đảng ủy phường",
    "Chi bộ Cơ quan Ủy Ban Mặt trận Tổ quốc Việt Nam phường",
    "Chi bộ Hội đồng nhân dân phường",
    "Chi bộ Văn phòng Hội đồng nhân dân và Ủy ban nhân dân phường",
    "Chi bộ Phòng Văn hóa - Xã hội phường",
    "Chi bộ Phòng Kinh tế, Hạ tầng và Đô thị phường",
    "Chi bộ Trung tâm Phục vụ Hành chính công phường",
    "Chi bộ Trung tâm Cung ứng Dịch vụ Sự nghiệp công phường",
    "Chi bộ Ban Quản lý dự án đầu tư xây dựng phường",
    "Chi bộ Quân sự",
    "Chi bộ Trạm Y tế",
    "Chi bộ Công ty Cổ phần Túi xách Đà Nẵng",
    "Chi bộ BIDV Văn phòng đại diện tại thành phố Đà Nẵng",
    "Chi bộ Công ty Bảo hiểm PJICO Đà Nẵng",
    "Chi bộ Công ty CP Tư vấn XD và Đầu tư Trường Định",
    "Chi bộ Ngân hàng TMCP An Bình Chi nhánh Đà Nẵng",
    "Chi bộ Công ty Bảo Minh Đà Nẵng",
    "Chi bộ Ngân hàng TMCP Tiên Phong Chi nhánh ĐN",
    "Chi bộ Trường Trung học phổ thông Quang Trung (tư thục)",
    "Chi bộ VPĐD Miền Trung Ngân Hàng TMCP Kỹ Thương Việt Nam",
    "Chi bộ Công ty Cổ phần Dịch vụ bảo vệ An Ninh",
    "Chi bộ Công ty Cổ phần Tư vấn và Phát triển kỹ thuật Tài nguyên nước",
    "Chi bộ Công ty Cổ phần Xây lắp Điện và Cơ khí mạ Đà Nẵng",
    "Chi bộ Trung tâm Giáo dục thường xuyên số 2",
    "Chi bộ Trường Trung học phổ thông Thái Phiên",
    "Chi bộ Công ty Trách nhiệm hữu hạn Dịch vụ Bảo vệ an ninh Quốc Đô",
    "Chi bộ Trung tâm Huấn luyện VĐV trẻ Quốc gia",
    "Chi bộ Trường Trung học phổ thông Thanh Khê",
    "Chi bộ Trường Mầm non Mẫu Đơn",
    "Chi bộ Trường Mầm non Tuổi Hoa",
    "Chi bộ Trường Mầm non Hải Đường",
    "Chi bộ Trường Mầm non Cẩm Nhung",
    "Chi bộ Trường Mầm non Tường Vy",
    "Chi bộ Trường Tiểu học Đoàn Thị Điểm",
    "Chi bộ Trường Tiểu học Huỳnh Ngọc Huệ",
    "Chi bộ Trường Tiểu học Dũng Sĩ Thanh Khê",
    "Chi bộ Trường Tiểu học Đinh Bộ Lĩnh",
    "Chi bộ Trường Tiểu học Trần Cao Vân",
    "Chi bộ Trường Tiểu học Hoa Lư",
    "Chi bộ Trường Trung học cơ sở Phan Đình Phùng",
    "Chi bộ Trường Trung học cơ sở Nguyễn Chơn",
    "Chi bộ Trường Trung học cơ sở Nguyễn Trãi",
    "Chi bộ Trường Trung học cơ sở Chu Văn An",
    "Chi bộ Trường Trung học cơ sở Huỳnh Thúc Kháng",
    "Chi bộ Tổng Công ty Miền Trung - CTCP",
    "Chi bộ Cty TNHH Kiểm toán & DV tin học Moore Aisc tại ĐN",
    "Chi bộ Công ty Cổ phần Giám định Á Việt",
    "Chi bộ Công ty Cổ phần Xây dựng Giao thông 503",
    "Chi bộ Công ty Cổ phần Sinh học Minh Hồng",
    "Chi bộ Trường Trung cấp Chuyên nghiệp Ý Việt",
  ]
}
];

// Danh sách phẳng toàn bộ (dùng để kiểm tra hợp lệ / autocomplete)
const DS_CHI_BO = DS_NHOM.flatMap(nhom => nhom.danhSach);

// Danh sách phẳng kèm nhóm (dùng cho giao diện modal chọn theo nhóm)
const DS_CHI_BO_FULL = DS_NHOM.flatMap(nhom =>
  nhom.danhSach.map(ten => ({ nhom: nhom.ten, ten }))
);